available_lengths = [
    25.4,
    25.4,
    25.4,
    50.8,
    50.8,
    50.8,
    76.2,
    76.2,
    76.2,
    101.6,
    101.6,
    101.6,
    127,
    127,
    127,
    152.4,
    152.4,
    152.4,
    203.2,
    203.2,
    254,
    254,
    304.8,
    304.8,
    355.6,
    355.6,
    406.4,
    406.4,
    457.2,
    457.2,
    508,
    508,
]
mount_style = "american_precision"
name = "Heavy Box Punch"
notes = "Heavy duty box punch for thicker materials and deep boxes"
style = "box"

[[features]]
id = "tip_contact"
role = "functional"

[features.geometry]
type = "ray"

[features.geometry.data]
angle = 270
position = [
    -41.275,
    -42.567065,
]

[[features]]
id = "tip_angle"
role = "reference"

[features.geometry]
type = "angle"

[features.geometry.data]
angle = 90

[[features]]
id = "tip_radius"
role = "reference"

[features.geometry]
type = "arc"

[features.geometry.data]
center = [
    -41.275,
    -42.17019,
]
radius = 0.396875

[[features]]
family = "american_precision"
gender = "male"
id = "mount_shoulder"
role = "mount"
style = "shoulder"

[features.geometry]
type = "ray"

[features.geometry.data]
angle = 90
position = [
    -41.275,
    46.332935,
]

[[features]]
family = "american_precision"
gender = "male"
id = "mount_tongue"
role = "mount"
style = "tongue"

[features.geometry]
type = "ray"

[features.geometry.data]
angle = 90
position = [
    -41.275,
    59.032935,
]
