available_lengths = [
    25.4,
    25.4,
    25.4,
    50.8,
    50.8,
    50.8,
    76.2,
    76.2,
    76.2,
    101.6,
    101.6,
    101.6,
    127,
    127,
    127,
    152.4,
    152.4,
    152.4,
    203.2,
    203.2,
    254,
    254,
    304.8,
    304.8,
    355.6,
    355.6,
    406.4,
    406.4,
    457.2,
    457.2,
    508,
    508,
]
mount_style = "american_precision"
mount_type = "t_slot"
name = "V-Die 88Â° 14ga"
notes = "American Precision Style V-die for 14 gauge material"
style = "v_die"

[[features]]
id = "v_opening"
role = "functional"

[features.geometry]
type = "offset"

[features.geometry.data]
angle = 90
end = [
    23.01875,
    0,
]
start = [
    7.14375,
    0,
]

[[features]]
id = "v_angle"
role = "reference"

[features.geometry]
type = "angle"

[features.geometry.data]
angle = 88

[[features]]
id = "v_tip_radius"
role = "reference"

[features.geometry]
type = "arc"

[features.geometry.data]
center = [
    15.08125,
    -7.076874,
]
radius = 0.79375

[[features]]
id = "shoulder_radius"
role = "reference"

[features.geometry]
type = "arc"

[features.geometry.data]
center = [
    6.81,
    -0.794,
]
radius = 0.794

[[features]]
family = "american_precision"
gender = "male"
id = "mount_shoulder"
role = "mount"
style = "shoulder"

[features.geometry]
type = "ray"

[features.geometry.data]
angle = 270
position = [
    15.08125,
    -44.196,
]

[[features]]
family = "american_precision"
gender = "male"
id = "mount_tongue"
role = "mount"
style = "tongue"

[features.geometry]
type = "ray"

[features.geometry.data]
angle = 270
position = [
    15.08125,
    -56.896,
]
