available_lengths = [
    25.4,
    25.4,
    25.4,
    50.8,
    50.8,
    50.8,
    76.2,
    76.2,
    76.2,
    101.6,
    101.6,
    101.6,
    127,
    127,
    127,
    152.4,
    152.4,
    152.4,
    203.2,
    203.2,
    254,
    254,
    304.8,
    304.8,
    355.6,
    355.6,
    406.4,
    406.4,
    457.2,
    457.2,
    508,
    508,
]
mount_style = "american_precision"
mount_type = "t_slot"
name = "V-Die 88Â° 20ga"
notes = "American Precision Style V-die for 20 gauge material"
style = "v_die"

[[features]]
id = "v_opening"
role = "functional"

[features.geometry]
type = "offset"

[features.geometry.data]
angle = 90
end = [
    16.98625,
    0,
]
start = [
    6.82625,
    0,
]

[[features]]
id = "v_angle"
role = "reference"

[features.geometry]
type = "angle"

[features.geometry.data]
angle = 88

[[features]]
id = "v_tip_radius"
role = "reference"

[features.geometry]
type = "arc"

[features.geometry.data]
center = [
    11.91,
    -55.34,
]
radius = 0.794

[[features]]
id = "shoulder_radius"
role = "reference"

[features.geometry]
type = "arc"

[features.geometry.data]
center = [
    6.660378,
    -0.390769,
]
radius = 0.390769

[[features]]
family = "american_precision"
gender = "male"
id = "mount_shoulder"
role = "mount"
style = "shoulder"

[features.geometry]
type = "ray"

[features.geometry.data]
angle = 270
position = [
    11.90625,
    -43.434,
]

[[features]]
family = "american_precision"
gender = "male"
id = "mount_tongue"
role = "mount"
style = "tongue"

[features.geometry]
type = "ray"

[features.geometry.data]
angle = 270
position = [
    11.90625,
    -56.134,
]
